name: Build Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest-large, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build test on ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Download the Likwid toolsuite
      run: curl -Lk https://github.com/RRZE-HPC/likwid/archive/refs/tags/v5.4.1.zip -o release.zip

    - name: Extract
      run: unzip release.zip

    - name: Build
      run: |
        cd likwid-5.4.1
        make likwid-topology
        sudo make install likwid-topology

    - name: Print system information
      run: |
        likwid-topology -g
