name: Build Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build test on ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_ACCESS }}
        ref: main

    - name: Setup Repo
      run: |
        git config user.name "${{ secrets.OWNER_NAME }}"
        git config user.email "${{ secrets.OWNER_EMAIL }}"
        git config pull.rebase true

    - name: Download the Likwid toolsuite
      run: curl -Lk https://github.com/RRZE-HPC/likwid/archive/refs/tags/v5.4.1.zip -o release.zip

    - name: Extract
      run: unzip release.zip

    - name: Build
      run: |
        cd likwid-5.4.1
        make
        sudo make install

    - name: Print system information
      run: |
        UTC_TIME=$(date -u +"%Y-%m-%dT%H-%M-%S.%NZ")
        OS_NAME=$(awk -F'=' '/^NAME/{name=$2} /^VERSION_ID/{version=$2} END{print substr(name,2,length(name)-2) "_" substr(version,2,length(version)-2)}' /etc/os-release)
        mkdir -p logs
        OUTPUT="${{ env.OS_NAME }}-${{ env.UTC_TIME }}.txt"
        uname -a > logs/${{ env.OUTPUT }}
        likwid-topology -g >> logs/${{ env.OUTPUT }}
        git add logs/${{ env.OUTPUT }}
        git commit -m "Added the system information of the current run"
        git pull
        git push -u origin main
